name: Build
on:
  pull_request:
    branches: [master, main]
  push:
    branches: [master, main]

jobs:
  build:
    runs-on: ${{matrix.operatingsystems}}
    env:
      BUILD_TYPE: ${{matrix.buildtypes}}
    strategy:
      matrix:
        operatingsystems: [ubuntu-latest]
        buildtypes: [Release]
    steps:
    - uses: actions/checkout@v4

    # Schlinux setup    
    - name: Setup Dependencies under Linux
      if: runner.os == 'Linux'
      run: |
        mkdir -p ~/.cache/apt ~/.local/share/apt
        sudo apt-get update
        sudo apt-get install -y clang-17 llvm-17 llvm-17-dev cmake ninja-build
      env:
        DEBIAN_FRONTEND: noninteractive

    - name: Configure Cmake under Linux
      if: runner.os == 'Linux'
      run: cmake -D CMAKE_C_COMPILER=clang-17 -D CMAKE_CXX_COMPILER=clang-17  -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G Ninja
    
    - name: Building Project
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      